//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.28 at 06:08:17 PM CET 
//



@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns={
                @XmlNs(prefix="tns", namespaceURI="http://jpk.mf.gov.pl/wzor/2016/10/26/10261/")
                ,@XmlNs(prefix="etd", namespaceURI="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2016/01/25/eD/DefinicjeTypy/")
        }

)
package com.malucha.jpkstructure2.xml;

import javax.xml.bind.annotation.XmlNs;